name: Build VulkanEngine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set Up CMake
      run: |
        sudo apt-get install -y cmake
        mkdir build
        cd build
        cmake ..
    
    - name: Build
      run: cmake --build build --config Release
